test = 1

try:
    print(test)

except:
    print("error")
    